version: "3.9"
services:
  duplicati:
    container_name: duplicati
    image: lscr.io/linuxserver/duplicati:latest #https://hub.docker.com/r/linuxserver/duplicati
    restart: always
    environment:

      #PUID - UserID
      #PGID - GroupID
      #TZ - Specify a timezone to use
      #CLI_ARGS - Optionally specify any CLI variables you want to launch the app with

      PUID: 1001
      PGID: 100
      TZ: America/Chicago

    volumes:
      - /srv/appdata/duplicati/config:/config
      - /srv/backups:/backups
      - /srv/mergerfs/mergerfs-pool1/pictures:/pictures
      - /srv/mergerfs/mergerfs-pool1/music:/music

    ports:
      - "8200:8200"
