version: '3.4'

services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    dns:
      - 1.1.1.1
      - 1.0.0.1	
    cap_add:
      - net_admin
    devices:
      - '/dev/net/tun:/dev/net/tun:rwm'
    environment:
      FIREWALL: ''
      PUID: 1000 #change to the uid of the admin user
      PGID: 1000 #change to the guid of the admin user
      TZ: America/Chicago
      VPN_AUTH: 'pia_username;pia_password'
      VPN_FILES: 'switzerland.ovpn;ca.rsa.2048.crt'
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /srv/appdata/vpn/:/vpn

  qbittorrent:
    container_name: qbittorrent  
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=1000 #change to the uid of the mediauser user
      - PGID=1000 #change to the gid of the mediauser user
      - TZ=America/Chicago
      - WEBUI_PORT=8080
    volumes:
      - /srv/appdata/qbittorrent/config:/config
      - /srv/dev-disk-by-uuid-00000000-0000-0000-0000-000000000000/torrents:/downloads
      - /srv/dev-disk-by-uuid-00000000-0000-0000-0000-000000000000/movies:/movies
      - /srv/dev-disk-by-uuid-00000000-0000-0000-0000-000000000000/shows:/shows

networks:
  default:
